### ISSUE TITLE
Password showing in clear

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#10]
**Describe the bug**
When wanting to change the password, both values (old and new password) are showed in clear.

We should hide them with a `type="password"` in the HTML input tag.
https://www.w3schools.com/Tags/att_input_type_password.asp 

**Screenshots**
![image](https://user-images.githubusercontent.com/33259633/162527440-1aadef4e-8cba-4b29-a27c-a23aa982c094.png)

**Additional context**

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
> **Describe the bug** When wanting to change the password, both values (old and new password) are showed in clear.
> 
> We should hide them with a `type="password"` in the HTML input tag. https://www.w3schools.com/Tags/att_input_type_password.asp
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/33259633/162527440-1aadef4e-8cba-4b29-a27c-a23aa982c094.png)
> 
> **Additional context** Add any other context about the problem here.
> 
> Thanks for contributing to ClassQuiz!

Thanks for pointing it out, completely forgot to change it!
