### ISSUE TITLE
Login via username and password

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#104]
Allow login via username and password next to email and password

**Comment by Dynnammo** [comment]
I would better have a single form for login, with a first box labelled "Username or email" and the password for the second box.

Many services like GitHub or Kahoot! use this as it's easier for the user to have a single form.

![image](https://user-images.githubusercontent.com/33259633/190396050-3fc4ec0e-72a6-4a18-be70-743c084257a0.png)
![image](https://user-images.githubusercontent.com/33259633/190396161-396e5ff0-d5a5-4281-87b2-977a80b96214.png)
