### ISSUE TITLE
Menu header not coming back after coming back from Play

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#11]
**Describe the bug**
When I click on play and then come back to main pages, the header with options (register, settings etc.) do not appear anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/33259633/162528963-5353333a-ac66-4426-9f46-fb7fc782601e.png)

https://www.loom.com/share/5e52369126d94ee2afd49b28319c4bc6

**Additional context**

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
> **Describe the bug** When I click on play and then come back to main pages, the header with options (register, settings etc.) do not appear anymore
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/33259633/162528963-5353333a-ac66-4426-9f46-fb7fc782601e.png)
> 
> https://www.loom.com/share/5e52369126d94ee2afd49b28319c4bc6
> 
> **Additional context** Add any other context about the problem here.
> 
> Thanks for contributing to ClassQuiz!

OK, noted! Will be fixed either tomorrow or Sunday. The same is also valid for #10 ! 

**Thank you for finding all these small bugs!** ❤️

**Comment by mawoka-myblock** [comment]
Fixed in https://github.com/mawoka-myblock/ClassQuiz/commit/411064967f095fcb1e04cf70dd402549771fd7ef
