### ISSUE TITLE
Sentences untranslated on classquiz main view

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#115]
### Which component is affected?

main page

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

1. Go to main page
2. See footer untranslated despite choosing another language

### Describe the bug (with screenshots if possible)

![image](https://user-images.githubusercontent.com/33259633/190397502-5fe3fb98-1849-4182-8abf-608f6e6a8446.png)

### Device

Laptop/Notebook

### Operating System

Linux

### Browser

Brave

**Comment by mawoka-myblock** [comment]
Strange... I definitely added it to the translations, but it doesn't work, soo...

**Comment by mawoka-myblock** [comment]
In dev-mode it works...
![grafik](https://user-images.githubusercontent.com/66328166/190729450-bfe9ddc2-d861-4b6d-a315-f5f9df2b551f.png)

**Comment by mawoka-myblock** [comment]
The problem seems to be that this string gets put in at build-time, so the language at build-time is english. It doesn't happen with other translations, since this one uses the `{@html }`-tag, so the link can be displayed correctly.
