### ISSUE TITLE
Fix flake8 errors

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#119]
**Describe the change and why it is needed**

- [ ] Ignore files in `./migrations/versions/`
- [ ] Fix mistakes in other files

**Additional context**
Run `flake8 .` at the project's root to list linting mistakes

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
There is even a deactivated worklflow/github action for flake8

**Comment by jonathan-d-zhang** [comment]
Alright. Do you want me to just go through and fix every flake8 error?

**Comment by mawoka-myblock** [comment]
> Alright. Do you want me to just go through and fix every flake8 error?

If you want, but configuring it correctly is a good start!

**Comment by jonathan-d-zhang** [comment]
Alright. I think flake8 would be good to add to pre-commit and gh actions also.

**Comment by mawoka-myblock** [comment]
Yes! Sure! If we have it in pre-commit, it'll automatically check, since I am using pre-commit.ci
