### ISSUE TITLE
Sign Out button in navbar

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#12]
**Describe the bug**
It would be great to have a disconnect button, similarly to Login, on the top right of the header.

**Screenshots**
![image](https://user-images.githubusercontent.com/33259633/162532400-d27b57ab-7bb4-486f-a038-b5ba7c5330d3.png)

**Additional context**

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
> **Describe the bug** It would be great to have a disconnect button, similarly to Login, on the top right of the header.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/33259633/162532400-d27b57ab-7bb4-486f-a038-b5ba7c5330d3.png)
> 
> **Additional context** Add any other context about the problem here.
> 
> Thanks for contributing to ClassQuiz!

Do you mean a sign out button?

**Comment by Dynnammo** [comment]
Yes.

**Comment by mawoka-myblock** [comment]
Yes, way harder than it should be, but I'll do it!
