### ISSUE TITLE
Remove Scroll Bar for larger screens and beautify it for smaller ones

### ISSUE THREAD

**Issue by developer-diganta** [mawoka-myblock/ClassQuiz#125]
![image](https://user-images.githubusercontent.com/65999534/193094420-6786f083-6de5-49bb-8d09-12a848d7b5a1.png)
The scroll bar can be removed for larger screens. Also, it can be beautified for the smaller ones according to the theme of the website. If it seems a good idea, can I work on it?

**Comment by mawoka-myblock** [comment]
Yes, please! Go ahead! It should be pretty simple, but please try to use Tailwind instead of "raw" css!
