### ISSUE TITLE
Add styling to password-change-boxes in account-settings

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#126]
![Unbenannt](https://user-images.githubusercontent.com/66328166/193123392-7f9ed10f-cb79-435a-a9a4-934ce2b4665c.png)
These white boxes aren't styled yet, so this could be an easy task. Design-inspirations can be taken from [Flowbite](https://flowbite.com/). It's located on the account-page at https://classquiz.de/account/settings

**Comment by LyndonFan** [comment]
I've happy to give this a go -- would it be possible to assign the task to me?

**Comment by mawoka-myblock** [comment]
> I've happy to give this a go -- would it be possible to assign the task to me?

For sure!

**Comment by LyndonFan** [comment]
I was trying to see what the page looked like on the website for myself, so attempted to register for an account. But after I put in my details, I didn't receive an email. I tried this for multiple google accounts and none of them worked. Is this a possible bug or did I miss something from the registration process?
On another note, is there a way to preview the account page without logging in? I tried running npm run deliver but it's missing the api (which makes sense -- I'm just running the front end 😅)

**Comment by mawoka-myblock** [comment]
> I was trying to see what the page looked like on the website for myself, so attempted to register for an account. But after I put in my details, I didn't receive an email. I tried this for multiple google accounts and none of them worked. Is this a possible bug or did I miss something from the registration process? On another note, is there a way to preview the account page without logging in? I tried running npm run deliver but it's missing the api (which makes sense -- I'm just running the front end 😅)

The email didn't arrive from your own, local instance, right? If so, set the env-var `SKIP_EMAIL_VERIFICATION` to `True`, so that the email is confirmed automatically. After you set it, register again.

**Comment by LyndonFan** [comment]
I was trying to register on the live website though...

**Comment by mawoka-myblock** [comment]
> I was trying to register on the live website though...

OK, thanks for pointing that out!

**Comment by mawoka-myblock** [comment]
> I was trying to register on the live website though...

It's fixed. I've unintentionally disabled email-verification, so all your email-addresses are confirmed without an email sent. It's now back on, so now emails will be sent.

**Comment by LyndonFan** [comment]
Hi there. I'm a bit busy at the moment, so won't be able to implement the feature. Sorry!

**Comment by mawoka-myblock** [comment]
> Hi there. I'm a bit busy at the moment, so won't be able to implement the feature. Sorry!

No problem, but still thank you for finding another issue ;)

**Comment by BoltUltra** [comment]
Hi, I would like to work on this styling, if you don't mind assigning me to the issue.

**Comment by mawoka-myblock** [comment]
Go ahead! Just open a PR if you're done!

**Comment by mawoka-myblock** [comment]
@BoltUltra sorry, I just did it myself, since this is issue was very old and easy.
