### ISSUE TITLE
Automatically select question when a new one is added in the editor

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#127]
If you add a new question in the editor, the pervious one is still selected, which can be annoying, so it would make sense that the newly created question will be selected automatically.

**Comment by basil08** [comment]
Hi, I would like to work on this :)

**Comment by mawoka-myblock** [comment]
> Hi, I would like to work on this :)

Sure!

**Comment by mawoka-myblock** [comment]
Any progress, @basil08?
