### ISSUE TITLE
Improve the footer style

### ISSUE THREAD

**Issue by yasirobai99** [mawoka-myblock/ClassQuiz#130]
**Describe the bug**
The footer of the website is not at all looking good so I would like the do some changes

**Screenshots**
Look at the footer it is not at all looking good
![Screenshot from 2022-10-01 01-52-25](https://user-images.githubusercontent.com/83706868/193351294-7947e854-7692-4721-88b9-b99fe8c44d16.png)

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
Go ahead! Do your changes and if you're done, we'll discuss them!

**Comment by Debajyoti111** [comment]
@mawoka-myblock  is this issue still available? If yes, then I would like to take it.

**Comment by mawoka-myblock** [comment]
Yes, you can, but I'm not sure if I'll merge it, since I honestly don't know how to improve the footer, but if you know what you could do, do so!
