### ISSUE TITLE
Make the size of images to be the same on player's screen and admin

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#133]
The images shouldn't have a fixed height/width, but they should have a proper max-width, but also keeping the aspect-ratio. I mean the pages, when the game gets played.

**Comment by gogoiakash2311** [comment]
hey, @mawoka-myblock can you assign this to me?

**Comment by mawoka-myblock** [comment]
> hey, @mawoka-myblock can you assign this to me?

Of course!
