### ISSUE TITLE
Make the game-pin shorter and check if agme with the same pin already exists

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#134]
The function here has to be adapted: https://github.com/mawoka-myblock/ClassQuiz/blob/master/classquiz/routers/quiz.py#L91
It should check if a redis-key with the following "key" exists: `game:GAME_PIN`. If so, generate a new game pin.

**Comment by npv12** [comment]
hey @mawoka-myblock can you assign this to me?

**Comment by mawoka-myblock** [comment]
> hey @mawoka-myblock can you assign this to me?

For sure! If you need help, just reach out!

**Comment by npv12** [comment]
> > hey @mawoka-myblock can you assign this to me?
> 
> For sure! If you need help, just reach out!

Can you let me which file https://github.com/mawoka-myblock/ClassQuiz/blob/master/start.sh#L4 refers to? I am trying to run it locally and was having trouble since /app/main.py doesn't exists

**Comment by mawoka-myblock** [comment]
> > > hey @mawoka-myblock can you assign this to me?
> > 
> > 
> > For sure! If you need help, just reach out!
> 
> Can you let me which file https://github.com/mawoka-myblock/ClassQuiz/blob/master/start.sh#L4 refers to? I am trying to run it locally and was having trouble since /app/main.py doesn't exists

Ah, yes! This file is docker-only. To start all the dependencies, use `./run_tests +` (no, it doesn't run the tests). Then run uvicorn, the frontend and caddy. It should be documented under classquiz.de/docs/develop
