### ISSUE TITLE
Add a Copy-to-clipboard-Button to the admin-screen to quickly copy the Game-PIN

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#137]
This is probably self-explaining. The Game-PIN should be visible on the screen, not only in the URL or the QR-Code.

**Comment by akk312000** [comment]
Can i work on this?

**Comment by mawoka-myblock** [comment]
Yes, sure! You're fast! If you need help, just reach out!

**Comment by akk312000** [comment]
I can give this a try @mawoka-myblock

**Comment by Priyanshu-su30** [comment]
I would like to work on this issue please assign me this

**Comment by mawoka-myblock** [comment]
So you both want to work on this= @Priyanshu-su30 @akk312000 ?

**Comment by Priyanshu-su30** [comment]
pls assign me this @akk312000 will find another issue

**Comment by mawoka-myblock** [comment]
> pls assign me this @akk312000 will find another issue

Honestly, if you ask like this, I'd prefer assigning this issue to @akk312000, since he also asked before you. Sorry! I'll ping you for sure, if I have a new issue for the hacktoberfest!

**Comment by mawoka-myblock** [comment]
@akk312000 Oh, sorry, I've just noticed, that it is already there, but a button to easily copy the Game-PIN to the clipboard was requested! Sorry!

**Comment by workspace-utkarsh** [comment]
Is the issue still open? I'd like to contribute.

**Comment by mawoka-myblock** [comment]
If @akk312000 won't respond within the next 7 days, yes, you can work on it.

**Comment by akk312000** [comment]
@workspace-utkarsh , you can have this issue.

**Comment by workspace-utkarsh** [comment]
Thankyou for assigning me the task.
I'm unable to understand how to proceed further since the Webapp is not working on my PC(Unable to login, Create a Quiz etc ). I'm unable to understand the full functionality.
Please help.

**Comment by mawoka-myblock** [comment]
> Thankyou for assigning me the task.
I'm unable to understand how to proceed further since the Webapp is not working on my PC(Unable to login, Create a Quiz etc ). I'm unable to understand the full functionality.
Please help.

The webapp only works if the backend is running as well. Please have a look at the docs on how to set ClassQuiz up for development-purposes: https://classquiz.de/docs/develop If you should still have any questions, reach out!

**Comment by mawoka-myblock** [comment]
I've noticed that this is already finished!
