### ISSUE TITLE
Implement custom answer-colors in practice-mode and on the public-quiz-page

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#138]

**Comment by mawoka-myblock** [comment]
Do you think @Priyanshu-su30, that you can do that?

**Comment by Priyanshu-su30** [comment]
> Do you think @Priyanshu-su30, that you can do that?

I m new to this open source, will try my best

**Comment by mawoka-myblock** [comment]
> Hi ! I am currently very new to open source world so could you please tell me where to make changes in this repository and will this be counted as a valid request for Hacktoberfest 2022?

Yes, but I've promised @Priyanshu-su30 to assign him this issue. Sorry, but I'll ping you if I have a new one!

**Comment by Priyanshu-su30** [comment]
> > Hi ! I am currently very new to open source world so could you please tell me where to make changes in this repository and will this be counted as a valid request for Hacktoberfest 2022?
> 
> Yes, but I've promised @Priyanshu-su30 to assign him this issue. Sorry, but I'll ping you if I have a new one!

can u brief me with this task

**Comment by mawoka-myblock** [comment]
> > > Hi ! I am currently very new to open source world so could you please tell me where to make changes in this repository and will this be counted as a valid request for Hacktoberfest 2022?
> > 
> > 
> > Yes, but I've promised @Priyanshu-su30 to assign him this issue. Sorry, but I'll ping you if I have a new one!
> 
> can u brief me with this task

Yo, you'll have to modify https://github.com/mawoka-myblock/ClassQuiz/blob/master/frontend/src/routes/view/%5Bquiz_id%5D/%2Bpage.svelte and https://github.com/mawoka-myblock/ClassQuiz/blob/master/frontend/src/lib/practice/question.svelte . You'll have to adapt the background-color like this: https://github.com/mawoka-myblock/ClassQuiz/blob/master/frontend/src/lib/play/question.svelte#L122

Are you familiar with HTML?

**Comment by Priyanshu-su30** [comment]
> > > > Hi ! I am currently very new to open source world so could you please tell me where to make changes in this repository and will this be counted as a valid request for Hacktoberfest 2022?
> > > 
> > > 
> > > Yes, but I've promised @Priyanshu-su30 to assign him this issue. Sorry, but I'll ping you if I have a new one!
> > 
> > 
> > can u brief me with this task
> 
> Yo, you'll have to modify https://github.com/mawoka-myblock/ClassQuiz/blob/master/frontend/src/routes/view/%5Bquiz_id%5D/%2Bpage.svelte and https://github.com/mawoka-myblock/ClassQuiz/blob/master/frontend/src/lib/practice/question.svelte . You'll have to adapt the background-color like this: https://github.com/mawoka-myblock/ClassQuiz/blob/master/frontend/src/lib/play/question.svelte#L122
> 
> Are you familiar with HTML?

ok i got it
Yes i am familiar with HTML and CSS
