### ISSUE TITLE
Add rounds to Quizz

### ISSUE THREAD

**Issue by IVEN2022** [mawoka-myblock/ClassQuiz#142]
IN Quiz editor , we can select to add rounds , for example each 5 questions we can put a break , as a title to the next round , and then it will be displayed in the admin area and in the players screen , we can name this round feature  . a select button can be added to the round so for exmaple double the score or tribble it . but OPTIONAL .

**Comment by Priyanshu-su30** [comment]
i would like to work on this pls assign me

**Comment by mawoka-myblock** [comment]
> i would like to work on this pls assign me

Do the other thing first

**Comment by Priyanshu-su30** [comment]
i had submitted the prev work
i can work on this too

**Comment by mawoka-myblock** [comment]
Ok, fine!

**Comment by Priyanshu-su30** [comment]
Sorry i didn't understand the task 
can u explain it

**Comment by IVEN2022** [comment]
BumpUP
