### ISSUE TITLE
Super Admin

### ISSUE THREAD

**Issue by IVEN2022** [mawoka-myblock/ClassQuiz#151]
Super Admin can login , but he have an admin page where all the registered users email and info , he can delete user , block user and his email , add user and password , or promote user to admin , Super Admin have the ability to delete any quiz made by any user , incase this quiz have an issue  or reported .

**Comment by mawoka-myblock** [comment]
I don't think that it would be worth the time I'd put into this feature.

**Comment by mawoka-myblock** [comment]
To clarify things: **I won't work on this issue**, because it's not worth putting the time into it.

**Comment by IVEN2022** [comment]
how then we suppose to ban someone or know who is using the system

**Comment by mawoka-myblock** [comment]
I'll create a cli-tool to delete quizzes, users, etc
