### ISSUE TITLE
Automatically assign colors to each answer on quizzes imported from Kahoot!

### ISSUE THREAD

**Issue by trygve55** [mawoka-myblock/ClassQuiz#158]
When importing a quiz from Kahoot all answers get assigned the same color. If each answer got a distinct color assigned it would cause less confusion by quiz participants.

**Comment by mawoka-myblock** [comment]
Another good idea from you, but which colors could I take? Do you gave any ideas, since the color-palette of ClassQuiz only consists of 3 colors? I'll work on that when I'll have time after the exams thus and next week (Maybe even earlier)

**Comment by trygve55** [comment]
I think the color palette from the site linked below could do well, the colors are distinct and also colorblind friendly.
https://davidmathlogic.com/colorblind/#%23D81B60-%231E88E5-%23FFC107-%23004D40

**Comment by trygve55** [comment]
Update suggestion: Add a default color palette for all quizzes or the option to have the option to select one when creating a new quiz.

I just ran a quiz with the color blind friendly palette "True" from the link above and it worked well. But it was a bit of work adding colors manually to every question.

**Comment by mawoka-myblock** [comment]
> Update suggestion: Add a default color palette for all quizzes or the option to have the option to select one when creating a new quiz.
> 
> I just ran a quiz with the color blind friendly palette "True" from the link above and it worked well. But it was a bit of work adding colors manually to every question.

Yes. If you create a quiz from scratch, the colors from the first question should be the default for all others in the quiz.

**Comment by mawoka-myblock** [comment]
But I really like the idea with choosing a color palette.

**Comment by mawoka-myblock** [comment]
But also a big "thank you" for actively telling me what's wrong and not abandoning ClassQuiz!
