### ISSUE TITLE
Quiz not supported for import

### ISSUE THREAD

**Issue by tch1001** [mawoka-myblock/ClassQuiz#159]
I like the idea of an open source kahoot! Thanks for this awesome project! I tried importing my kahoot slides but I get this error

![Screenshot 2022-10-23 at 7 41 32 PM](https://user-images.githubusercontent.com/17665556/197390110-bbc0e9ba-e5ae-48b4-948b-92ffdab877da.png)

**Comment by mawoka-myblock** [comment]
Could you please send the link to the kahoot-quiz you've entered into the box?

**Comment by tch1001** [comment]
https://create.kahoot.it/share/functions/4154d0c5-ee7c-4ea4-aba7-208cb44ac7be
https://create.kahoot.it/details/4154d0c5-ee7c-4ea4-aba7-208cb44ac7be

both links do not work :) thanks for looking into it! appreciate the open source work

**Comment by mawoka-myblock** [comment]
> https://create.kahoot.it/share/functions/4154d0c5-ee7c-4ea4-aba7-208cb44ac7be https://create.kahoot.it/details/4154d0c5-ee7c-4ea4-aba7-208cb44ac7be
> 
> both links do not work :) thanks for looking into it! appreciate the open source work

The first link also shouldn't work, since the one with the `details` in the URL is correct. I quickly looked at the quiz and you don't seem to use any unsupported features, so the import should work. Will try it and tell you or fix it what's going on! Thank you for pointing this issue out!

**Comment by mawoka-myblock** [comment]
Found the problem: The slides are not supported and you had some.

**Comment by tch1001** [comment]
Ah thanks! Would be useful to perhaps ignore those slides at least, and let the rest pass maybe, just a suggestion! Thanks for the great work

**Comment by mawoka-myblock** [comment]
> Ah thanks! Would be useful to perhaps ignore those slides at least, and let the rest pass maybe, just a suggestion! Thanks for the great work

Will do that!

**Comment by mawoka-myblock** [comment]
I've had a look into that and it it way more complex than I've thought. I think I won't implement this anytime soon, sorry.
