### ISSUE TITLE
Move critical variables inside secrets

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#16]
There's a bunch of variables showed in clear in the code see [config.py](https://github.com/mawoka-myblock/ClassQuiz/blob/master/classquiz/config.py) with Sentry and Imgur vars for instance.

We should move those variables inside env variables , since people installing classquiz should rely on their own credentials

**Comment by mawoka-myblock** [comment]
Removed imgur (unused) and sentry should stay, so it is enabled by default on self-hosted instances.
