### ISSUE TITLE
Add blocking by cookie for the Voting Question

### ISSUE THREAD

**Issue by IVEN2022** [mawoka-myblock/ClassQuiz#160]
Add A BLOCKING BY cookie for the Voting Question , So people cant vote more than once , the BLOCK cookie should be selected optional inside the VOTING edit , and if possible to be able to tell how long the blocking will be by (HOURS) , but also people can join other game id`s if they are already voted . WHAT IS THE POSSIBILITIES here .

**Comment by mawoka-myblock** [comment]
Players can vote just once per question, I don't see why we should need a cookie for that.
