### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by caland001** [mawoka-myblock/ClassQuiz#163]
Hello, it seems like I'm encountering some bugs here. If I try to register with my email, I don't get a confirmation mail. If I try to register with gidhub, I get:

'''
Error authenticating
GitHub didn't respond with an email-address. Are you sure your email-address is verified?

[Go back to login-page](https://classquiz.de/account/login)
If the error persists, please open an [issue on GitHub](https://github.com/mawoka-myblock/ClassQuiz/issues/new?assignees=&labels=&template=Bug_report.md).
'''
even tho I have verified my email. If I try to register with gmail, I get:

'{"detail":"duplicate key value violates unique constraint \"users_pkey\"\nDETAIL: Key (id)=(00000xxx00x00x00xx000000000000x0) already exists."}'

My key was different from the one I quoted there, but I changed it because I didn't knew if it was maybe a private key.

Tomorrow I need to make the quiz because I want to use it in my high school lesson on Monday. You think you could fix this before then?

Best Regards and thank you for making this!

**Comment by mawoka-myblock** [comment]
Ok. It will work until Monday. You have 2 options for now: either register with another email-address (if you use gmail, you can use prefixes with + as far as I know), or send me your email-address, so I can verify your email-address manually. If you send me your email-address, contact me at https://mawoka.eu/contact

**Comment by caland001** [comment]
Thank you very mutch for your quick responce! I will sent you an email with my mailadres.

**Comment by mawoka-myblock** [comment]
I unfortunately didn't receive your email (if you've sent it). Please try again sending the mail to `mawol at pm dot me`
