### ISSUE TITLE
Reduce number of countdown timers and combine them on question slides

### ISSUE THREAD

**Issue by trygve55** [mawoka-myblock/ClassQuiz#165]
**Describe the bug**
Right now there is 3 countdown timers. 

If you combine the two top ones (centered number and reverse progress bar) it will give more space on the page for content and also look better. This can be done by placing the number on top of the reverse progress bar centered vertically and something like ~10% margin from the left end.

The circle countdown could possibly be moved to the left side.

Thank you so much for working on this project!

**Comment by mawoka-myblock** [comment]
Thank you for the idea! I apologize for the late reply.

**Comment by trygve55** [comment]
No problem! Keep up the awesome work. :)

**Comment by mawoka-myblock** [comment]
Like this? 
![grafik](https://user-images.githubusercontent.com/66328166/201911248-06cdae6a-a00e-42f1-ad99-bba532d29d67.png)

**Comment by trygve55** [comment]
Yes, almost. I was thinking of moving it to the side like this to make more space if an image was included with the question. Without a image I think the current layout looks good.
![image](https://user-images.githubusercontent.com/10439755/204332245-9bc78207-cee7-4262-bb95-86ee4c5fe2d3.png)

**Comment by mawoka-myblock** [comment]
If I am honest, it looks kinda lost if i is off-center like this. I agree that it takes up space, but it is (in my opinion) visually appealing.
