### ISSUE TITLE
Add minimal CI with Github Actions

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#17]
**Describe the change and why it is needed**
An open-source project attract a community when people see that even if it's under heavy development, it is battlefield-tested with a bunch of automatic tools that check linting, tests etc.

We should have a minimal CI. To begin with :

- [ ] python linting ([flake8](https://pypi.org/project/flake8/) as instance
- [ ] svelte/js linting
- [ ] test suite for python (pytest already used)

**Additional context**
I'm acquainted with such work, I could work on it if I'm becoming Triage/Maintain member of this project.

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
- If you run flake8, please run it like this: `flake8 --max-line-length 120 classquiz`
- If you run pytest, please only if sth changes in either `classquiz/storage`, `classquiz/tests` or `classquiz/kahoot_importer`
- If you run svelte-linitng, please use pnpm, not npm and run `pnpm check` and `pnpm lint`

**Comment by mawoka-myblock** [comment]
Do you consider these tools enught:
- DeepSource
- Snyk
- Pytest
?

**Comment by mawoka-myblock** [comment]
i think that this is done!
