### ISSUE TITLE
Add extra media file formats (video)

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#171]
I'd like to be able to add a video to the slide, not only pictures. This is very useful when using ClassQuiz in a teaching context.
Either adding a video file, or a URL liking to a youtube video for example.

**Comment by mawoka-myblock** [comment]
Some thoughts about this: If I/we would add support for videos, we have 2 options, each has their own drawback:

- Using **YouTube**: Privacy.
- Using **self-hosted** (like the images now): Storage.

I don't like neither of them. Maybe Vimeo, but I doubt that they're better than YouTube in this regard.
