### ISSUE TITLE
After first reply, the next slides show only the count down bar

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#177]
### Which component is affected?

Admin-screen when game running

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

1. lauch game
2. join
3. answer first question
4. see results and go to next question
5. nothing is displayed.

Tried on Brave and safari, same issue. 

### Describe the bug (with screenshots if possible)

![2SW8XK7MF6](https://user-images.githubusercontent.com/17297189/202916794-7068ec6b-bef0-447c-8ee1-c1cd80bfdc0c.gif)

### Device

Laptop/Notebook

### Operating System

macOS Ventura 13.0.1

### Browser

Brave 1.45.127, Safari 16.1

**Comment by mawoka-myblock** [comment]
Working on it
