### ISSUE TITLE
Results page graph should use answer button color

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#178]
After answering a question, the results page displays a graph with the numbers of votes or selected answer. The graph is all black, would be nicer and more readable to have the graph display the bars with the same color as the answer? (I display the question screen on an auditorium with 300 seats... thus the displayed text in the graph is sometimes hard to read from the far seats).

**Comment by mawoka-myblock** [comment]
So do you think the text should be bigger as well, next to "custom colors" for the bars?

**Comment by RicoLaaa** [comment]
Yes probably the text should be bigger as well.

The thing is, the graph is not centered horizontally/vertically to the window. So it gets cropped if the window is too small (see first picture. And the response text is overlapping the graph (second pic).

Maybe everything should be displayed horizontally, this would allow for longer and bigger text display.

<img width="1198" alt="Capture d’écran 2022-11-20 à 22 01 09" src="https://user-images.githubusercontent.com/17297189/202926032-e213d12f-0db5-4667-848a-b527581ce680.png">

<img width="659" alt="Capture d’écran 2022-11-20 à 22 01 31" src="https://user-images.githubusercontent.com/17297189/202926042-8b52189f-a944-4904-b3ee-eecbea6ed4fd.png">
