### ISSUE TITLE
export results button is hidden on top of the page

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#179]
### Which component is affected?

admin-screen at the end of game

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

play and finish a game until the export results button is displayed

### Describe the bug (with screenshots if possible)

<img width="654" alt="Capture d’écran 2022-11-20 à 21 40 53" src="https://user-images.githubusercontent.com/17297189/202925448-c6cfafce-a004-4257-b3a6-1c7be9a9113d.png">

### Device

Laptop/Notebook

### Operating System

macOS Ventura 13.0.1

### Browser

Brave 1.45.127

**Comment by RicoLaaa** [comment]
The issue is still there on my side...

**Comment by mawoka-myblock** [comment]
Ah, yes the changes aren't yet live on ClassQuiz.de, but they should be in 5 minutes

**Comment by mawoka-myblock** [comment]
Should be live, just like the formatting of the title, question-titles and description. (Only with HTML-Tags (for now))
