### ISSUE TITLE
Make images full-screen on click during a game

### ISSUE THREAD

**Issue by terrenay** [mawoka-myblock/ClassQuiz#182]
I'm missing this feature on a deck I've imported from Kahoot. It relies heavily on code shown in an image, which is rendered very small by ClassQuiz and can thus not be read by the students.

**Comment by mawoka-myblock** [comment]
That's definitely a good idea which can be very useful!

**Comment by mawoka-myblock** [comment]
Sorry that this has taken soo long... I hope that this makes ClassQuiz now more useful for you!
