### ISSUE TITLE
Question displayed as title

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#185]
### Which component is affected?

admin-screen when game is running

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

I've filled up a question with a lorem ipsum place holder. 
The title displays the same text as the question and there is no way to hide it or write a proper title. (check attached screenshot)

### Describe the bug (with screenshots if possible)

<img width="1310" alt="Capture d’écran 2022-12-03 à 17 40 15" src="https://user-images.githubusercontent.com/17297189/205451813-c8d10afc-550d-49c9-b924-6d369ac60fc6.png">

### Device

Desktop

### Operating System

macOS 13.0.1

### Browser

Brave 1.45.131

**Comment by mawoka-myblock** [comment]
I don't get what you mean. If possible, could you contact me using an instatnt-messenger (Discord, or look at https://mawoka.eu/contact)?
