### ISSUE TITLE
Center count down timer on the screen

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#186]
**Describe the bug**
The timer is displayed on the top of the screen, pushing the answer buttons down.
Would be nicer to have it displayed in the center of the page.(see screenshot)
Same for the button pics, they should be centered on the button.

**Screenshots**
![image](https://user-images.githubusercontent.com/17297189/205452214-4bd682bc-fbcb-4b79-9de8-c542c35dbe36.jpeg)

**Comment by mawoka-myblock** [comment]
Great idea! Will do that! I really like it! Also thanks for the mockup! ❤️

**Comment by mawoka-myblock** [comment]
![Bildschirmfoto am 2022-12-03 um 18 07 59](https://user-images.githubusercontent.com/66328166/205452970-5014bd33-e641-49b9-a31d-3a5d30997d2b.png)

**Comment by RicoLaaa** [comment]
the icons are not centered on the buttons like on your screen shot (Safari on iOS).
But the centered timer looks beautiful now !
