### ISSUE TITLE
Api Error while Setup

### ISSUE THREAD

**Issue by DerKartdomi** [mawoka-myblock/ClassQuiz#191]
Hello, I tried to install qlassquiz with docker. when I do docker ps I get the error that the API restarts itself. just look at logs "ValueError: deta_key and deta_id must be provided". What should I do?

**Comment by mawoka-myblock** [comment]
Please make sure that you read the installations docs carefully. It says that you have to choose a storage for the images. The option is called `STORAGE_BACKEND`. You should set this to `local`. If you search [this](https://classquiz.de/docs/self-host) page for "Storage provider", you'll find further instructions. If the issue should still come up, just reopen this issue.

**Comment by DerKartdomi** [comment]
How to set the directory?

**Comment by DerKartdomi** [comment]
I created a directory but it says invalid syntax

**Comment by mawoka-myblock** [comment]
Just set the next environment-varaiable as well: `STORAGE_PATH: "/var/storage"`. Then mount that path into a docker volume or so. This isn't explained in the docs (yet), but here is a snippet:
```yaml
    volumes:
      - ./uploads:/var/storage
```
This will mount `/var/storage` from the container into the local folder, `uploads`.
