### ISSUE TITLE
Can't see the background color selector when set to white

### ISSUE THREAD

**Issue by RicoLaaa** [mawoka-myblock/ClassQuiz#194]
### Which component is affected?

Editor

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

When editor interface is set to light color, the background of the first page is white, the color selector border is white as well, so if the selected background color is set to white, everything fades in the background and becomes invisible. 
See attached screenshot, you can see the default background, the switch, but not the bkg color selector.
Happens on safari, not on brave (both display different color pickers as well)

### Describe the bug (with screenshots if possible)

<img width="264" alt="Capture d’écran 2022-12-27 à 22 57 13" src="https://user-images.githubusercontent.com/17297189/209726195-833aee95-8be9-4130-94d5-9cdcf76794d3.png">

### Device

Laptop/Notebook

### Operating System

macOS 13.1

### Browser

Safari 16.2

**Comment by mawoka-myblock** [comment]
A colored border around the selector should solve the issue, correct?
