### ISSUE TITLE
QR Code in Dark Mode not readable with some Apps

### ISSUE THREAD

**Issue by ThexXTURBOXx** [mawoka-myblock/ClassQuiz#205]
### Which component is affected?

Admin screen

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

Start a game with Dark Mode enabled

### Describe the bug (with screenshots if possible)

The QR Code in dark mode is not readable with some Apps since it is negated.
As far as I know, the ISO/IEC 18004:2015 does not explicitly allow or define "negated" QR codes, so maybe it would be better to always show the normal QR Code with a white background (and a small white border), even with dark mode enabled.

See this example which does not work with the stock Camera app from Xiaomi, but works with QRDroid:

![grafik](https://user-images.githubusercontent.com/12763829/218829531-75d18471-d619-48f3-829d-68ae4284697a.png)

### Device

Laptop/Notebook

### Operating System

Windows

### Browser

Firefox

**Comment by mawoka-myblock** [comment]
Will fix that, thank you for pointing that out. Never thought about it, since I've tested it and it worked.
