### ISSUE TITLE
"Real" Multiple choice

### ISSUE THREAD

**Issue by ThexXTURBOXx** [mawoka-myblock/ClassQuiz#206]
**Describe the feature**
It would be very nice if you could mark multiple answers as correct, but also allow users to choose multiple answers in their response.

**Screenshots**
For example, in the following image, three answers are correct, but when a user plays the game, they can only choose one answer.
Adding this feature would allow users to get all the points only if they guess all the correct answers (and partial amounts or no points at all otherwise).
Kahoot does have this feature, but it is not free.

![grafik](https://user-images.githubusercontent.com/12763829/218831001-46d00a83-e60b-49fe-a990-a8eb3f05413a.png)

**Comment by mawoka-myblock** [comment]
Good idea, will work on that!

**Comment by mawoka-myblock** [comment]
Do you have any idea on how to name this question type?

**Comment by ThexXTURBOXx** [comment]
Thank you very much for the fast response!
I am really unsure on how to name it. As far as I know, Kahoot calls this feature "Multiple choice" and the currently implemented one "Single Choice". However, I don't really like that naming scheme since it is not really "Single" Choice. It's rather "Multiple choice, but you only have to guess one correct answer".
I will try to find out if there is a standardized name for that, but I am unsure

**Comment by mawoka-myblock** [comment]
Thank you! Otherwise I'll have to come up with a ~good~ name, just like "order", "range" or "text"-answers...

**Comment by ThexXTURBOXx** [comment]
You're welcome!
According to Wikipedia, it looks like the current approach could be called "Multiple Choice: Choose" or "Single Choice". However, also these ones are both not really the right name for it. I am in doubt if there is really a standardized name for it.
The name of the approach I am suggesting would certainly be "Multiple Choice: Check", though.

**Comment by mawoka-myblock** [comment]
What about Check Choice(s)?

**Comment by mawoka-myblock** [comment]
Oh, and I haven't already worked on it, since working some other (unnecessary) features made more fun, sorry for that!
I hope that I'll find some motivation in the coming days/hours/weeks/months.

**Comment by ThexXTURBOXx** [comment]
> What about Check Choice(s)?

That also sounds good! I would probably prefer "Check Choice" since it better coincides with "Multiple/Single Choice".

> I haven't already worked on it

No problem at all, I know exactly what you mean :) You don't need an excuse for anything. I would rather need to thank you for working on this in your free time!

**Comment by mawoka-myblock** [comment]
But I can also thank you for the fast reply ;)

**Comment by mawoka-myblock** [comment]
Would you be happy to do the testing? ;)

**Comment by ThexXTURBOXx** [comment]
Of course, any time :D

**Comment by mawoka-myblock** [comment]
Go ahead, live in ~2 minutes at classquiz.de

**Comment by mawoka-myblock** [comment]
Only thing not yet implemented is the practice-mode nobody is using anyway

**Comment by mawoka-myblock** [comment]
Ok, everything I can think of is now implemented

**Comment by mawoka-myblock** [comment]
Testing is still very much appreciated ;)

**Comment by ThexXTURBOXx** [comment]
Thank you very much! That worked very well already :)
I just found a small issue: It might be good to "highlight" which answers you had selected. Right now, if you select some answers, it is not visualised:

https://github.com/mawoka-myblock/ClassQuiz/assets/12763829/420fe921-1d4e-4228-838f-549b158aa0dc

Apart from that, the calculation of the points is working properly and I have found no other issues :)

**Comment by mawoka-myblock** [comment]
Sure, I implemented that, let me check that quickly if that may be a mobile-only issue

**Comment by mawoka-myblock** [comment]
Works on firefox

**Comment by ThexXTURBOXx** [comment]
I tried also on Firefox and it seems to have the same issue even though the style is being changed on click:

https://github.com/mawoka-myblock/ClassQuiz/assets/12763829/cc94fdac-f4a4-43c4-9489-52331ff3fb5d

**Comment by mawoka-myblock** [comment]
Ah, I think I know why! Since I am using the "opacity-100" (which is applied by clicking it) nowhere else, the tailwind compiler doesn't include it in the final bundle! Will have to fix that tomorrow! (This is just an idea)

**Comment by ThexXTURBOXx** [comment]
Thank you very much for fixing that, it works now fine on my devices! :)

**Comment by mawoka-myblock** [comment]
Now comes the next question: What should I call this in German?

**Comment by ThexXTURBOXx** [comment]
A literal translation would be "Prüfauswahl", of course, but I don't know if people would immediately understand what that means from the name.

**Comment by mawoka-myblock** [comment]
> A literal translation would be "Prüfauswahl", of course, but I don't know if people would immediately understand what that means from the name

Exactly that is the problem. Maybe a help-button next yo the question selector could clarify things. Would you still choose " Prüfauswahl"? I think that is translation is bad and nobody would get it.

**Comment by ThexXTURBOXx** [comment]
A small question mark next to the name would be great, indeed. I also think nobody would get it any other way.
Something like this hover button in Overleaf would maybe be a good solution (the tooltip appears when hovering over the "i"):
![grafik](https://github.com/mawoka-myblock/ClassQuiz/assets/12763829/a0688467-bb5e-445e-84ac-2aaf04a4a2cf)
