### ISSUE TITLE
Question buttons aren't in the same location as in the admin screen if 4 answers are given

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#213]

**Comment by trygve55** [comment]
We encountered the same problem, it's causing a lot of fustration.

Usually its answer alternative 2 and 3 switching places.

**Comment by mawoka-myblock** [comment]
Ah, yes! Thank you for reminding me of that!

**Comment by mawoka-myblock** [comment]
Follow-Up: #218
