### ISSUE TITLE
Show answer distribution after a question.

### ISSUE THREAD

**Issue by trygve55** [mawoka-myblock/ClassQuiz#216]
**Describe the bug**
Adding this to the screen after a question would be a fun improvement. It will allow everyone to see how many(with percentages) got the correct answer.

A bar diagram with each answer alternative as a column, with the number of players that picked the alternative shown. The wrong answers could be faded so you can see the correct answer.

This could be added to the side or bottom of the screen when showing the top players and their score increases.

Quick paint sketch:
![after question screen](https://user-images.githubusercontent.com/10439755/227527737-6e0bddc3-456c-4f44-b46c-db6a6993f7f8.png)

**Comment by mawoka-myblock** [comment]
Like we already have for vote-questions?

**Comment by trygve55** [comment]
I didn't know about that feature. But yes, very much like that.

**Comment by trygve55** [comment]
Yes, I tested a vote question slide.
