### ISSUE TITLE
Inform users about Command Palette

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#250]
I've just added a command palette. How can I inform the user about it? It can be opened by pressing
<kbd>Meta</kbd>+<kbd>k</kbd> (<kbd>Ctr</kbd>+<kbd>k</kbd> or <kbd>⌘</kbd>+<kbd>k</kbd>).

(@Dynnammo)

**Comment by Dynnammo** [comment]
Many options : 
1) In the case you plan to introduce more keyboard shortcuts, I think of the example of Excalidraw [here](https://excalidraw.com/), where a panel pop up when you click on the *?* button at the bottom right, displaying all available options
2) In case it's the single main command plan, a single-appearing popup after connection can prevent users, with a gif in it , showing all possible commands
3) Nice feature btw

**Comment by mawoka-myblock** [comment]
If some more possible commands come to your mind, don't hesitate telling me!
