### ISSUE TITLE
Rectangles in slides have no option to change colour.

### ISSUE THREAD

**Issue by ATMmachin3** [mawoka-myblock/ClassQuiz#269]
### Which component is affected?

Quiz editor, slide panel.

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

Create a slide and add a Rectangle, then attempt to modify it's colour using the colour picker button.
It is not possible to click the colour picker button.
![Screen Shot 2023-08-04 at 7 19 59 PM](https://github.com/mawoka-myblock/ClassQuiz/assets/85604438/1fcbeec8-240d-40ed-95f4-cd4ea4ce355c)
For comparison, the colour picker is white for a circle, where I am able to click it.
![Screen Shot 2023-08-04 at 7 20 14 PM](https://github.com/mawoka-myblock/ClassQuiz/assets/85604438/0e871559-3d25-4b79-83f9-cb3e5fbba311)

### Describe the bug (with screenshots if possible)

Rectangle colour is unable to modified in a slide.

### Device

Desktop

### Operating System

Tested on Linux, MacOS

### Browser

Firefox

**Comment by mawoka-myblock** [comment]
Will try that now

**Comment by ATMmachin3** [comment]
Works perfectly now, many thanks!
