### ISSUE TITLE
Design - Incorrect display rectangle when connecting

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#27]
⚠️ The main ClassQuizz instance at (https://classquizz.mawoka.eu/) uses Sentry as a bug detection software, so please disable your AdBlocker if you want to ease the debug process ⚠️

**Describe the bug**
Wrong text display when connecting

**To Reproduce**
1. Go to connexion screen
2. Click on Emai
3. See error : email rectangle is displaying

**Expected behavior**
Having same display as password, like password rectangle not appearing

**Screenshots**
![image](https://user-images.githubusercontent.com/33259633/163593583-9d29b687-a9bd-46bb-b680-d9e6fd177a70.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device [e.g. iPhone6, Desktop]: Desktop
 - Device OS [e.g. iOS8.1, Windows 10]: Manjaro KDE 21
 - Browser [e.g. Chrome, Firefox, Safari]: Version 1.30.87 Chromium: 94.0.4606.71
 - ~~Classquiz Version [e.g. 0.10]:~~  :warning:** No versioning for now** :warning:
 - Classquiz installation [e.g. classquiz.mawoka.eu]:
 - Commit SHA [e.g : ed35c5c69019e7cd6331ea438519f53b8bce70cf]: 

**Additional context**

**Comment by mawoka-myblock** [comment]
Thank you for reporting this, @Dynnammo, but for now, I don't know how to fix it and, let's be honest, it's not important.

**Comment by Dynnammo** [comment]
Agree at a 100%,it would be good one for newbies joining the project. It may be the occasion to have a tagging system like this one on this project (https://github.com/metabase/metabase/issues) with `Priority:P1`, `Priority:P2` etc., allowing devs to focus on important issues ? It may be just overkill for now.

**Comment by mawoka-myblock** [comment]
> It may be the occasion to have a tagging system like this one on this project (https://github.com/metabase/metabase/issues) with `Priority:P1`, `Priority:P2` etc., allowing devs to focus on important issues ? It may be just overkill for now.

Exactly my thoughts
