### ISSUE TITLE
Show results button sometimes does not work

### ISSUE THREAD

**Issue by Aunsiels** [mawoka-myblock/ClassQuiz#277]
### Which component is affected?

Quiz view

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

Hi,
Sometimes, the button Show results stops working when no answer is submitted. For example:

- [ ] If everybody leaves
- [ ] If I press "Stop time and show results" too quickly
- [x] If nobody answers

### Describe the bug (with screenshots if possible)

Sometimes, the button Show results stops working when no answer is submitted.

### Device

Desktop

### Operating System

Linux

### Browser

Firefox

**Comment by mawoka-myblock** [comment]
Thank you soon much for telling when the button does not work! That's really helpful, otherwise I would have spent hours finding that

**Comment by mawoka-myblock** [comment]
All points had the same origin and are now fixed in https://github.com/mawoka-myblock/ClassQuiz/commit/40dba3e469cad72434747eac5eddf8d02f047963
