### ISSUE TITLE
Improve Player Interface

### ISSUE THREAD

**Issue by Aunsiels** [mawoka-myblock/ClassQuiz#278]
Here are some suggestions to improve the player interface:

- [x] When the admin shows the results, the players get the message "No answers!", which is a bit disturbing. Can we show a message like "Correct Answer" or "Right Answer"? (Edit by me (@mawoka-myblock): That was a bug that this wasn't working)
- [ ] At the end, can we print the rank of the player during the fireworks?

Thanks,

**Comment by mawoka-myblock** [comment]
All these ideas are great and I’ll look into implementing them!
