### ISSUE TITLE
Captcha fails again and again

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#28]
⚠️ The main ClassQuizz instance at (https://classquiz.mawoka.eu/) uses Sentry as a bug detection software, so please disable your AdBlocker if you want to ease the debug process ⚠️

**Describe the bug**
When wanting to register for a private game, it throws me away an error of captcha failure

**To Reproduce**
1. Create a private quiz
2. Start it
3. Try to connect to a game by going on classquiz and click Play
4. Fill the game pin
5. fill player name
6. See error

**Expected behavior**
It should return me the waiting page, and for the game creator show me that a user entered.

**Screenshots**
[Video for bug description](https://www.loom.com/share/a32ba4b8f9f14feebf24557d649b76c8)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device [e.g. iPhone6, Desktop]: PC
 - Device OS [e.g. iOS8.1, Windows 10]: MAnjaro KDE
 - Browser [e.g. Chrome, Firefox, Safari]: Version 1.30.87 Chromium: 94.0.4606.71
 - ~~Classquiz Version [e.g. 0.10]:~~  :warning:** No versioning for now** :warning:
 - Classquiz installation [e.g. classquiz.mawoka.eu]: 
 - Commit SHA [e.g : ed35c5c69019e7cd6331ea438519f53b8bce70cf]: 

**Additional context**

**Comment by mawoka-myblock** [comment]
Could you please try to reload the page with `Ctrl` and `F5`?

**Comment by mawoka-myblock** [comment]
Seems to be an issue with hCaptcha or the way I implemented it (it wasn't really me, it was a stranger from StackOverflow).

**Comment by mawoka-myblock** [comment]
This is "now" fixed by using reCaptcha instead of hCaptcha.
