### ISSUE TITLE
Create a quizz without need to create an account

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#29]
**Describe the feature**
As Classquizz is a project in early development, it would be greqt to eqse the process of quiz creation by letting people create quiz without the need to register.

The process could look followingly :

1. Main page having a button "Create a quiz now!"
2. Redirecting to the creation of a quizz
3. Quizz creation workflow
4. Quizz play workflow
5. At the end of the game, having a message suggesting to create an account to save the quizz permanently

**Screenshots**
If applicable, add screenshots to help explain your feature.

**Additional context**

Thanks for contributing to ClassQuiz!

**Comment by mawoka-myblock** [comment]
This won't happen since nobody should be able to upload images without an account.
