### ISSUE TITLE
Randomizing quiz answers breaks when using range questions

### ISSUE THREAD

**Issue by tyll** [mawoka-myblock/ClassQuiz#323]
When a quiz contains a range question, randomizing quiz answers creates an exception. At least this is my assumption given that I saw this fail in this condition and it seems that range questions have a dict instead of a list as answers, therefore `random.shuffle()` fails:
https://github.com/mawoka-myblock/ClassQuiz/blob/d1a97ca85de573a9ab14e15dbbf0fdf51aac2bf2/classquiz/routers/quiz.py#L108

**Comment by mawoka-myblock** [comment]
But it worked in the past...

**Comment by mawoka-myblock** [comment]
@tyll  Just saw your donation: Thank you soo much ❤️ !
