### ISSUE TITLE
Order question shown "Unknown Question Type (shouldn't happen)"

### ISSUE THREAD

**Issue by webafrancois** [mawoka-myblock/ClassQuiz#325]
### Which component is affected?

admin-screen in edit mode

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

When I add a question type "order" : Answers can be brought into the correct order
The thumbnail show "Unknown Question Type (shouldn't happen)"

### Describe the bug (with screenshots if possible)

![Sélection_1149](https://github.com/mawoka-myblock/ClassQuiz/assets/19719849/f12d413b-5ca5-424c-8b5d-5ac694a4d994)

### Device

Desktop

### Operating System

Linux Mint

### Browser

Firefox

**Comment by mawoka-myblock** [comment]
I am thinking of removing this preview in general, but "improving" and replacing the placeholders isn't a bad idea at all!
