### ISSUE TITLE
docker-compose.yml in repo out of sync with documentation and possibly broken

### ISSUE THREAD

**Issue by tyll** [mawoka-myblock/ClassQuiz#327]
Compare the docker-compose.yml from https://classquiz.de/docs/self-host and https://github.com/mawoka-myblock/ClassQuiz/blob/master/docker-compose.yml

The files are slightly different, the file from the docs seems to be broken in general. Colons instead of equal signs should be used here:

```
	  # If STORAGE_BACKEND is "s3"
	  S3_ACCESS_KEY=YOUR_ACCESS_KEY
	  S3_SECRET_KEY=YOUR_SECRET_KEY
	  S3_BASE_URL=YOUR_S3_BASE_URL
```

Also, for me there were complaints about using `True` instead of `"True"` in some lines, for example:

```
	  SKIP_EMAIL_VERIFICATION: True # Set this to skip sending emails
```

or https://github.com/mawoka-myblock/ClassQuiz/blob/master/docker-compose.yml#L74
Not sure if this is supposed to work or if this is wrong, this is the first time I tried docker-compose.

I am happy to provide a PR if you can provide some guidance about how it should look like, for example should the documentation yaml file be updated from the one in the repo and is change the boolean values to a string value correct.

**Comment by mawoka-myblock** [comment]
The `True` is supposed to work, but I think that's not a big problem. The do-co-file in the docs is there for demonstration purposes, not to bes used "as is". I'm gonna rework that part.
