### ISSUE TITLE
On mobile: Question covered by time slider

### ISSUE THREAD

**Issue by TheNomad11** [mawoka-myblock/ClassQuiz#359]
When the question is longer than one line on the mobile screen, the question (in "Old School" mode) is covered by the red time slider (or how the red line is called that displays the remaining time), see screenshot:

![signal-2024-04-07-193335](https://github.com/mawoka-myblock/ClassQuiz/assets/20747629/4a8efadb-894c-44db-919a-4cd11bab4267)

**Comment by mawoka-myblock** [comment]
I unfortunately can't reproduce it. Some details would be helpful like device and browser.

I still changed a tiny bit which may have helped, but as I can't reproduce it, it's really difficult to fix.

![image](https://github.com/mawoka-myblock/ClassQuiz/assets/66328166/afbdd90f-e57a-49f3-8492-53861e9a361d)

**Comment by TheNomad11** [comment]
Aha, that was with Firefox on Android 14, with Vivaldi there are no issues. What did you use? 
........ Now I have found the reason: In Firefox I had increased the font size to 125% in the settings, therefore! Setting it back to 100% solves the issue

**Comment by mawoka-myblock** [comment]
Ah, that makes sense. I wouldn't consider this to be an issue as it'd so much work to fix all these errors. Do you think that it's an issue in that sense or more of a user error?

**Comment by TheNomad11** [comment]
neither a big issue nor a user error in my view. just something one should know. it is not uncommon with increased font size. we can close it.
