### ISSUE TITLE
Kahoot import error 500

### ISSUE THREAD

**Issue by TheHomecraft** [mawoka-myblock/ClassQuiz#374]
### Which component is affected?

Kahoot-import

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

Take a Game from Kahoot (Original) and try to import it. Then the error will occur. A alert will pop up that states: "Kahoot replied with 500" This is A Screenshot from the Alert:

 ![image](https://github.com/mawoka-myblock/ClassQuiz/assets/92114751/f784af51-8303-4afc-9b65-a808b671b6e5)

### Describe the bug (with screenshots if possible)

The Error occures on both ClassQuiz.de and self-hosted instance. 

When Trying to import a Game from Kahoot, the operation fails and the Alert pop up from above will open.

Btw i used this Kahoot game: https://create.kahoot.it/details/45db2b22-f7d5-423c-8f99-2b1f1c8862f3

### Device

Desktop

### Operating System

Windows

### Browser

Opera-Gx

**Comment by mawoka-myblock** [comment]
ClassQuiz doesn't support the slide type.
