### ISSUE TITLE
There is no script /app/prestart.sh

### ISSUE THREAD

**Issue by guzdal** [mawoka-myblock/ClassQuiz#400]
### Which component is affected?

/gunicorn_conf.py

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

over Linux MINT, git cloned the whole repo and threw an eye at the docker-compose.yml for a full local installation (LAN)

### Describe the bug (with screenshots if possible)

`./start.sh 
Checking for script in /app/prestart.sh
There is no script /app/prestart.sh

Error: '/gunicorn_conf.py' doesn't exist
`

### Device

Laptop/Notebook

### Operating System

Linux MINT

### Browser

Firefox

Tried to have a look at the api container : 
`docker-compose exec api /bin/bash`
`ls`
`root@9216f263085c:/app# ls -l
total 216

-rw-rw-r-- 1 root root   1251 Sep 17 19:05 Pipfile

-rw-rw-r-- 1 root root 167935 Sep 17 19:05 Pipfile.lock

-rw-rw-r-- 1 root root     81 Sep 17 19:05 Pipfile.lock.license

drwxr-xr-x 2 root root   4096 Sep 17 20:45 __pycache__

-rw-rw-r-- 1 root root   3309 Sep 17 19:05 alembic.ini

drwxr-xr-x 1 root root   4096 Sep 17 20:45 classquiz

-rw-rw-r-- 1 root root   2074 Sep 17 19:05 gunicorn_conf.py

-rw-rw-r-- 1 root root    908 Sep 17 19:05 image_cleanup.py

drwxr-xr-x 1 root root   4096 Sep 17 20:45 migrations

-rw-rw-r-- 1 root root    108 Sep 17 19:05 prestart.sh

-rw-r--r-- 1 root root   1500 Sep 17 19:27 requirements.txt

-rwxrwxr-x 1 root root   1198 Sep 17 19:05 start.sh
`
Next I'm trying on an empty VM.
Or on WSL, but I'll try that again.

**Comment by mawoka-myblock** [comment]
The `start.sh` is only used inside the docker container, thus only works in there. For a guide on how to set everything up, check the [Self-Hosting guide]8https://classquiz.de/docs/self-host) or the [Dev guide](https://classquiz.de/docs/develop).

**Comment by guzdal** [comment]
Hello @mawoka-myblock ; so I did get it working using your documentation a couple of hours ago, may I please suggest something to clarify it?

Because it was actually working from the start but I couldn't even think of trying to throw **http://localhost:8000** on my web browser, once I got docker-compose working. 
I've had to check out the docker-compose.yml file one more time and add some slash somewhere. 

Plus the last command you're providing at the very bottom of the page, misses dashes between docker and compose :
`docker compose build && docker compose up -d`

However, to me, these suggestions don't seem to belong on this issue: I believe you can close it right away not to mess it up.
May I please DM them to you?

thanks a lot! 
[closed]!

**Comment by mawoka-myblock** [comment]
There are no hyphens missing. If you installed docker compose correctly, it ought to work like that. Feel free to contact me via DM. Find all the options for that over at https://mawoka.eu/contact

**Comment by guzdal** [comment]
oh really? 
OK. I did not know that, I always have installed using apt install docker docker-compose -y  ; thanks!
I might create one more Issue about some PNG files that won't be uploaded for some reason... I'll just keep testing not to flood this git.

Cheers!
