### ISSUE TITLE
Incorrect URL Paths When Deploying ClassQuiz Under a Subdirectory

### ISSUE THREAD

**Issue by Mergim1992** [mawoka-myblock/ClassQuiz#404]
### Which component is affected?

Frontend in general

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On a self-hosted instance

### How can the issue be reproduced?

Steps to Reproduce:
Deploy ClassQuiz under a subdirectory, such as /classquiz, using an NGINX proxy.
Access the app via https://domain.com/classquiz.
Click on buttons like "Play" or other navigation links. 
You will see that it redirects to https://domain.com/play instead of https://domain.com/classquiz/play

### Describe the bug (with screenshots if possible)

Clicking on buttons like "Play" directs users to https://domain.com/play instead of https://domain.com/classquiz/play.

### Device

Desktop

### Operating System

Linux Ubuntu 24.04

### Browser

Firefox, Safari

**Comment by mawoka-myblock** [comment]
Yea, subdirectory hosting won't ever be a thing as it'd be a lot of work rewriting all the URLs, but glad you figured that out on your own!
