### ISSUE TITLE
& encoding error

### ISSUE THREAD

**Issue by Cameo007** [mawoka-myblock/ClassQuiz#42]
⚠️ The main ClassQuizz instance at (https://classquizz.mawoka.eu/) uses Sentry as a bug detection software, so please disable your AdBlocker if you want to ease the debug process ⚠️

**Describe the bug**
ClassQuiz replaces  "&" characters in the description with "`&amp`;".

**To Reproduce**
1. Create a new Quiz and edit it
2. Go to description field
3. Enter your description with an "&" character
4. Save the quiz
5. Edit the quiz again and look at the description field OR start the quiz and look at the description

**Expected behavior**
I expected that the "&" character to remain an "&" character.

**Screenshots**

https://user-images.githubusercontent.com/80521473/164976817-5a2d3f2a-4d23-4107-990f-bbacc1bbbd0f.mp4

**Stacktrace**
/

**Extra data (please complete the following information):**
 - Device: Laptop, Samsung Galaxy A50, Apple iPad 7th Gen.
 - Device OS: Windows 10, Android 11, iPadOS 15.5 Public Beta
 - Browser: Chrome, Chrome, Safari & Chrome
 - ~~Classquiz Version [e.g. 0.10]:~~  :warning:** No versioning for now** :warning:
 - Classquiz installation [e.g. classquiz.mawoka.eu]:
 - Commit SHA [e.g : ed35c5c69019e7cd6331ea438519f53b8bce70cf]: 

**Additional context**
/

**Comment by mawoka-myblock** [comment]
> ⚠️ The main ClassQuizz instance at (https://classquizz.mawoka.eu/) uses Sentry as a bug detection software, so please disable your AdBlocker if you want to ease the debug process ⚠️
> 
> **Describe the bug** ClassQuiz replaces "&" characters in the description with "`&amp`;".
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Create a new Quiz and edit it
> 
>     2. Go to description field
> 
>     3. Enter your description with an "&" character
> 
>     4. Save the quiz
> 
>     5. Edit the quiz again and look at the description field OR start the quiz and look at the description
> 
> 
> **Expected behavior** I expected that the "&" character to remain an "&" character.
> 
> **Screenshots**
> ClassQuiz.issue.mp4
> 
> **Stacktrace** /
> 
> **Extra data (please complete the following information):**
> 
>     * Device: Laptop, Samsung Galaxy A50, Apple iPad 7th Gen.
> 
>     * Device OS: Windows 10, Android 11, iPadOS 15.5 Public Beta
> 
>     * Browser: Chrome, Chrome, Safari & Chrome
> 
>     * ~Classquiz Version [e.g. 0.10]:~  ⚠️** No versioning for now** ⚠️
> 
>     * Classquiz installation [e.g. classquiz.mawoka.eu]:
> 
>     * Commit SHA [e.g : [ed35c5c](https://github.com/mawoka-myblock/ClassQuiz/commit/ed35c5c69019e7cd6331ea438519f53b8bce70cf)]:
> 
> 
> **Additional context** /

You're totally right. I'll have to play a detective to find out where the character gets converted. I'll do that hopefully next week.

**Comment by vherrmann** [comment]
I still have this problem on the main instance
