### ISSUE TITLE
Add minimal instructions for contribution guidelines and issue creation

### ISSUE THREAD

**Issue by Dynnammo** [mawoka-myblock/ClassQuiz#6]
For development purposes, it would be great to create a `CONTRIBUTING.md` file and issues/PRs templates, as it allows developers and testers to easily create issues and PRs on the project.

**Comment by mawoka-myblock** [comment]
> For development purposes, it would be great to create a `CONTRIBUTING.md` file and issues/PRs templates, as it allows developers and testers to easily create issues and PRs on the project.

Good idea! Is this enough for `CONTRIBUTING.md` https://classquiz.mawoka.eu/docs/develop? Issue/PR-templates? I knew that they exist and that's it.

**Comment by Dynnammo** [comment]
Yes it seems, you could also check that [contributing file](https://github.com/decidim/decidim/blob/develop/CONTRIBUTING.adoc) as it gives more details on how to dive into issue creation and.

I'll make a PR with basic issue/PR template files.

**Comment by Dynnammo** [comment]
EDIT : will split github templates and contributing in separate PRs as it's not completely the same subject

**Comment by mawoka-myblock** [comment]
> EDIT : will split github templates and contributing in separate PRs as it's not completely the same subject

Contributing is already done in https://github.com/mawoka-myblock/ClassQuiz/commit/483ea6eac42e28eca1fbf60094c84c1e6250f594
