### ISSUE TITLE
Replace window.location.replace with window.location.assign

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#69]
## Why?
If the url was changed by window.location.replace, it's not available in the history. With window.location.assign, the user can navigate back.

**Comment by chriswolfdesign** [comment]
I will be happy to give this one a shot.

**Comment by mawoka-myblock** [comment]
> I will be happy to give this one a shot.
> 
> PR can be found here: #70
> 
> I apologize that I was not able to follow all workflow requirements, I need to get my machine more up to date with python and javascript. However, this issue is small enough that I imagine the CI/CD testing suite should handle any possible issues with this work.

It's not a big problem, that you couldn't run all the tests. As long as you don't misspell "assign", everything should be fine ;) If you find the contribution-docs unclear or got any questions, just contact me or open an issue (or even fix it yourself)!
