### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#77]
The test-coverage is at 76%, but it can be improved. The coverage is only for the backend (python)-part.

**Comment by mawoka-myblock** [comment]
*71%...

**Comment by khitab** [comment]
Let me give it a try. Thanks.

**Comment by mawoka-myblock** [comment]
> Let me give it a try. Thanks.

For sure! For help, reach out!

**Comment by khitab** [comment]
Hello @mawoka-myblock, I cloned and set up the pipenv as suggested [here](https://classquiz.de/docs/develop).

The part where environment variables are to be set is a bit unclear to me.

Is there documentation/code which shows how to do it?

**Comment by mawoka-myblock** [comment]
Take this as the `.env`-file.
```
ROOT_ADDRESS=http://localhost:8080
MAIL_ADDRESS=
MAIL_PASSWORD=
MAIL_USERNAME=
MAIL_SERVER=
MAIL_PORT=587
SECRET_KEY=mysecretkey
ACCESS_TOKEN_EXPIRE_MINUTES=30
SKIP_EMAIL_VERIFICATION=True
HCAPTCHA_KEY=0x0000000000000000000000000000000000000000
SENTRY_DSN=
STORAGE_BACKEND=local
STORAGE_PATH=/tmp/storage
MEILISEARCH_URL=http://127.0.0.1:7700
DB_URL=postgresql://postgres:mysecretpassword@localhost:5432/classquiz
```

Running tests will be done with `./run_tests.sh a`

**Comment by khitab** [comment]
That works. Thanks a lot.
