### ISSUE TITLE
Redo the "overview"-page

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/ClassQuiz#80]
A user mentioned that the overviwe-screen isn't very user-friendly and that's true. I honestly don't even know when I touched it the last time after creating it in like 10 mins, so it's time to redo it. Of you got any ideas on how it could look, please tell me!
@Dynnammo

**Comment by Dynnammo** [comment]
- [ ] I would suggest first to rename **Overview** to **Dashboard**, as it seems more common to me in many web apps.
- [ ] Set this page as the default one when connecting (right now, we're arriving on the presentation page of classquiz at classquiz.de)

Bonus : 
- it can be linked to a more global issue of redesigning the menu and colors of Classquiz

**Comment by mawoka-myblock** [comment]
I've done some work, but I am not 100% happy, but I also don't know what could be missing

**Comment by Dynnammo** [comment]
I've some ideas I wrote there, but the main look is great :tada:

**Comment by mawoka-myblock** [comment]
Since I've got positive feedback so far, I think I'll close this issue.
