### ISSUE TITLE
API container doesn't start

### ISSUE THREAD

**Issue by Cittjr** [mawoka-myblock/ClassQuiz#90]
### Which component is affected?

API container

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On a self-hosted instance

### How can the issue be reproduced?

Fill the docker compose like the documentation.

This is my Env data :

environment:
      - DB_URL="postgresql://postgres:classquiz@db:5432/classquiz"
      - MAIL_ADDRESS="xxx@xxx.com"
      - MAIL_PASSWORD="P@ssw0rd"
      - MAIL_USERNAME="xxx@xxx.com"
      - MAIL_SERVER="smtp.xxx.com"
      - MAX_WORKERS="1" # Very important
      - MAIL_PORT="587"
      - SECRET_KEY="MySecret"
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - SKIP_EMAIL_VERIFICATION=true
      - HCAPTCHA_KEY="HCAPTCHA_PRIVATE_KEY"
      - MEILISEARCH_URL="http://meilisearch:7700"
      - VITE_GOOGLE_AUTH_ENABLED=false
      - VITE_GITHUB_AUTH_ENABLED=false
      - STORAGE_BACKEND="local"
      - STORAGE_PATH="/var/storage"
      - REDIS=redis://redis:6379/0?decode_responses=true

### Describe the bug (with screenshots if possible)

When the API container start, i have this error

```
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/migrations/env.py", line 6, in <module>
    from classquiz.db.models import metadata
  File "/app/./classquiz/__init__.py", line 11, in <module>
    from classquiz.config import settings
  File "/app/./classquiz/config.py", line 61, in <module>
    redis: redis_base_lib.client.Redis = redis_lib.Redis().from_url(settings().redis)
  File "/app/./classquiz/config.py", line 58, in settings
    return Settings()
  File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings

t
  value is not a valid integer (type=type_error.integer)
```
I'm not a Python dev and i don't understand why setting are not valid !

### Device

Desktop

### Operating System

Debian Linux Docker

### Browser

All

**Comment by mawoka-myblock** [comment]
Thank you for submitting this error!

There are 2 things I've noticed:
- Your booleans (true/false) should be capitalized (**T**rue/**F**alse)
- Are you sure, that you've copied the complete output, because
> ```
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
�
t
  value is not a valid integer (type=type_error.integer)
```

looks a bit odd to me

**Comment by Cittjr** [comment]
thanks for your response, i use portainer and in the log i have this 

![image](https://user-images.githubusercontent.com/91184090/186933468-c2d4c96e-1b0c-4cf3-803e-2a8668798f37.png)

I test to capitalize the boolean value !

**Comment by mawoka-myblock** [comment]
> thanks for your response, i use portainer and in the log i have this
> 
> ![image](https://user-images.githubusercontent.com/91184090/186933468-c2d4c96e-1b0c-4cf3-803e-2a8668798f37.png)
> 
> I test to capitalize the boolean value !

Hmmm.
Is there any chance you can obtain the logs vie the command line? The command is (I think) `docker logs classquiz_api`

**Comment by Cittjr** [comment]
the logs in command line have the good error :
`ttings.py", line 38, in pydantic.env_settings.BaseSetting                                                                          s.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
mail_port
  value is not a valid integer (type=type_error.integer)
Checking for script in /app/prestart.sh`

I change all env to :

`    environment:
      - DB_URL=postgresql://postgres:classquiz@db:5432/classquiz
      - MAIL_ADDRESS="quiz@jeeo-web.com"
      - MAIL_PASSWORD="Azerty123!"
      - MAIL_USERNAME="quiz@jeeo-web.com"
      - MAIL_SERVER="smtp.jeeo-web.com"
      - MAX_WORKERS="1" # Very important
      - MAIL_PORT=587
      - SECRET_KEY="5722c89f1013f2f76fd3f2f3bc6d90784b70d24caf3ef1035ff99ba72d6c28dc"
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - SKIP_EMAIL_VERIFICATION=True
      - HCAPTCHA_KEY="HCAPTCHA_PRIVATE_KEY"
      - MEILISEARCH_URL="http://meilisearch:7700"
      - VITE_GOOGLE_AUTH_ENABLED=False
      - VITE_GITHUB_AUTH_ENABLED=False
      - STORAGE_BACKEND=local
      - STORAGE_PATH="/var/storage"
      - REDIS=redis://redis:6379/0?decode_responses=True`

But i have a new error :

`File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect

self.dbapi_connection = connection = pool._invoke_creator(self)

File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect

return dialect.connect(*cargs, **cparams)

File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect

return self.dbapi.connect(*cargs, **cparams)

File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect

conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "db" (172.19.0.5), port 5432 failed: FATAL: password authentication failed for user "postgres"`

The API doesn't Auth to se database !

**Comment by Cittjr** [comment]
I check to delete the previous volume off the DB.

Thanks for your support

**Comment by mawoka-myblock** [comment]
I've read your message and now know your credentials! I've deleted it, so nobody else will be able to read it. Did you change anything in the `db`-section?

**Comment by mawoka-myblock** [comment]
So is it fixed?

**Comment by Cittjr** [comment]
i have found my errors !!

In the docker compose, do not add " to the env variables !

It's works.

But i have specified "SKIP_EMAIL_VERIFICATION=True" and when i register an account a mail it's send !

**Comment by Cittjr** [comment]
it is also possible to remove the captcha when start a new game ?

**Comment by mawoka-myblock** [comment]
> SKIP_EMAIL_VERIFICATION

Ah, yea! Will fix that quickly?

> it is also possible to remove the captcha when start a new game ?

No, not at the moment and I don't plan this at the moment, since it would add extra complexity top the configuration in `frontend/Dockerfile`. If you want, I can add it.

**Comment by mawoka-myblock** [comment]
The `skip_email_verification`-thing is fixed. You just need to git-pull the changes.

**Comment by mawoka-myblock** [comment]
The captcha-thing is fixed, as well!

**Comment by mawoka-myblock** [comment]
> I use you beautiful app in a private network ;)

Oh, I've completely missed that part! Thank you 🥰

**Comment by Cittjr** [comment]
I have change directly in the database my user ;)

I have a last issue, when i add a png image in the quizz, after i have always an error popup when save the quizz !

i don't have an error in the API logs, only a 400 error log

172.19.0.5:40412 - "POST /api/v1/editor/finish?edit_id=e793fede HTTP/1.1" 400

I have create the directory /var/storage and i have set to 777.

The image is present in the folder but the response of the finish is => {"detail":"Image URL(s) aren't valid!"}
