### ISSUE TITLE
Error save quiz when added image

### ISSUE THREAD

**Issue by Cittjr** [mawoka-myblock/ClassQuiz#91]
### Which component is affected?

frontend

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On a self-hosted instance

### How can the issue be reproduced?

- Use local to save images
- Create a new quiz
- Upload an image
- Save the quiz

### Describe the bug (with screenshots if possible)

When i add a png image in the quizz, after i have always an error popup when save the quizz !

i don't have an error in the API logs, only a 400 error log

172.19.0.5:40412 - "POST /api/v1/editor/finish?edit_id=e793fede HTTP/1.1" 400

I have create the directory /var/storage and i have set to 777.

The image is present in the folder but the response of the finish is => {"detail":"Image URL(s) aren't valid!"}

### Device

Desktop

### Operating System

Linux

### Browser

All

**Comment by mawoka-myblock** [comment]
I can't reproduce this issue, but does the image show up in the editor?

If so, do you feel comfortable using the browser console? if so, please send me the `src` of the image. (If you right-click the image, you delete it it)

**Comment by Cittjr** [comment]
I upload the image, i view this, and the src in the editor is : <img src="https://quiz.xxx.com/api/v1/storage/download/980d587a-9053-4f00-8119-008dfb9e8460--5ec95252-ebda-4fe9-88c8-da1d20dfbcc8" alt="not available" class="max-h-72 h-auto w-auto">

**Comment by Cittjr** [comment]
The ROOT_ADDRESS is not present in my docker compose, i'm stupid.

It's works !!! 

Thanks for your support !
