### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by maxmasetti** [mawoka-myblock/ClassQuiz#93]
hi,

please add language italian.

thanks

**Comment by mawoka-myblock** [comment]
Done: https://translate.mawoka.eu/projects/classquiz/frontend/it/

**Comment by maxmasetti** [comment]
first translation done.
when pulled, I'm gonna install and reexamine thru inspecting the interface. Eventually I'll change something if it sounds bad.
thx
max

**Comment by mawoka-myblock** [comment]
Thank **YOU**! That's awesome and thank you for your work! You can test it on [ClassQuiz.de](https://classquiz.de) since I've deployed it already!
